# Generated by Django 5.0.2 on 2024-03-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
